os:
  - linux

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: mvn clean install

branches:
  only:
    - development
    - master

notifications:
  email: false