language: java
install: mvn clean install
jdk:
  - oraclejdk11
notifications:
  recipients:
    - cadox8@gmail.com
  on_success: never # default: change
  on_failure: always # default: always

branches:
  only:
    - gh-pages
    - /.*/